# Generated by Django 5.2.4 on 2025-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexfactory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexevent',
            name='acro_expand',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acro Expand'),
        ),
        migrations.AddField(
            model_name='forexevent',
            name='also_called',
            field=models.CharField(blank=True, max_length=255, verbose_name='Also Called'),
        ),
        migrations.AddField(
            model_name='forexevent',
            name='derived_via',
            field=models.TextField(blank=True, verbose_name='Derived Via'),
        ),
        migrations.AddField(
            model_name='forexevent',
            name='ff_notes',
            field=models.TextField(blank=True, verbose_name='FF Notes'),
        ),
        migrations.AddField(
            model_name='forexevent',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='forexevent',
            name='next_release',
            field=models.CharField(blank=True, max_length=100, verbose_name='Next Release'),
        ),
        migrations.AlterField(
            model_name='forexevent',
            name='measures',
            field=models.TextField(blank=True, verbose_name='Measures'),
        ),
        migrations.AlterField(
            model_name='forexevent',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='forexevent',
            name='usual_effect',
            field=models.TextField(blank=True, verbose_name='Usual Effect'),
        ),
        migrations.AlterField(
            model_name='forexevent',
            name='why_traders_care',
            field=models.TextField(blank=True, verbose_name='Why Traders Care'),
        ),
    ]
