# Generated by Django 5.2.4 on 2025-07-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexfactory', '0002_forexevent_acro_expand_forexevent_also_called_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexevent',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Source URL'),
        ),
    ]
