# Generated by Django 5.2.4 on 2025-07-16 06:05

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Используйте только латиницу, цифры, дефисы и подчеркивания', max_length=110, unique=True, verbose_name='URL-адрес (slug)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(help_text='Используйте только латиницу, цифры, дефисы и подчеркивания', max_length=110, unique=True, verbose_name='URL-адрес (slug)')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Используйте только латиницу, цифры, дефисы и подчеркивания', max_length=265, unique=True, verbose_name='URL-адрес (slug)')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('main_image', models.ImageField(help_text='Это изображение будет на карточке статьи в общем списке.', upload_to='article_images/', verbose_name='Главное изображение')),
                ('video_url', models.URLField(blank=True, help_text='Если указано, вместо изображения будет показано видео.', null=True, verbose_name='Ссылка на видео (YouTube, Vimeo)')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержимое статьи')),
                ('is_pinned', models.BooleanField(default=False, help_text='Закрепленная статья будет показана в большом блоке наверху.', verbose_name='Закрепить статью?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, to='articles.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
