# Generated by Django 5.2.4 on 2025-07-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForexEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Время события (МСК)')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('impact', models.CharField(choices=[('High', 'Высокое'), ('Medium', 'Среднее'), ('Low', 'Низкое')], max_length=10, verbose_name='Влияние')),
                ('event_name', models.CharField(max_length=255, verbose_name='Название события')),
                ('actual', models.CharField(blank=True, max_length=20, verbose_name='Факт.')),
                ('forecast', models.CharField(blank=True, max_length=20, verbose_name='Прогноз')),
                ('previous', models.CharField(blank=True, max_length=20, verbose_name='Пред.')),
                ('source', models.TextField(blank=True, verbose_name='Источник')),
                ('measures', models.TextField(blank=True, verbose_name='Что измеряет')),
                ('usual_effect', models.TextField(blank=True, verbose_name='Обычное влияние')),
                ('why_traders_care', models.TextField(blank=True, verbose_name='Почему это важно для трейдеров')),
                ('event_type', models.CharField(blank=True, max_length=50, verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'Событие Forex Factory',
                'verbose_name_plural': 'События Forex Factory',
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
