# Generated by Django 5.2.4 on 2025-07-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Размер счета')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Бюджет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название платформы')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='TraderExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Опыт трейдера')),
            ],
        ),
        migrations.CreateModel(
            name='TradingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Стиль торговли')),
            ],
        ),
        migrations.CreateModel(
            name='PropFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название фирмы')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='prop_logos/', verbose_name='Логотип')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Например, 4.9', max_digits=2, verbose_name='Рейтинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена от')),
                ('details_url', models.URLField(blank=True, max_length=500, verbose_name="Ссылка на 'Подробнее'")),
                ('pros', models.TextField(help_text='Каждый плюс с новой строки', verbose_name='Плюсы')),
                ('cons', models.TextField(help_text='Каждый минус с новой строки', verbose_name='Минусы')),
                ('account_sizes', models.ManyToManyField(to='propfirms.accountsize', verbose_name='Размеры счетов')),
                ('budgets', models.ManyToManyField(to='propfirms.budget', verbose_name='Бюджеты')),
                ('platforms', models.ManyToManyField(to='propfirms.platform', verbose_name='Платформы')),
                ('tags', models.ManyToManyField(blank=True, to='propfirms.tag', verbose_name='Теги')),
                ('trader_experiences', models.ManyToManyField(to='propfirms.traderexperience', verbose_name='Опыт трейдера')),
                ('trading_styles', models.ManyToManyField(to='propfirms.tradingstyle', verbose_name='Стили торговли')),
            ],
            options={
                'verbose_name': 'Проп-фирма',
                'verbose_name_plural': 'Проп-фирмы',
                'ordering': ['-rating'],
            },
        ),
    ]
